<section id="services" class="py-12 bg-white">
    <div class="max-w-xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8">
      <h2 class="sr-only">Fabrication at it's best!</h2>
      <dl class="space-y-10 lg:space-y-0 lg:grid lg:grid-cols-3 lg:gap-8">
        <div>
          <dt>
            <div class="flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
              <!-- Heroicon name: outline/globe-alt -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
              </svg>
            </div>
            <p class="mt-5 text-lg leading-6 font-medium text-gray-900">Chimney Inspections</p>
          </dt>
          <dd class="mt-2 text-base text-gray-500">
            A chimney inspection is a procedure in which an engineer examines a chimney for any signs of safety concerns or building code violations.  Our engineers will carefully analyze a chimney and also provide recommendations for improvement that would benefit you.  Inspections are usually done annually, before the ownership change, before a chimney project, or after an accident or fire involving a chimney.
          </dd>
        </div>
  
        <div>
          <dt>
            <div class="flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
              <!-- Heroicon name: outline/scale -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
              </svg>
            </div>
            <p class="mt-5 text-lg leading-6 font-medium text-gray-900">Exhaust System Inspections</p>
          </dt>
          <dd class="mt-2 text-base text-gray-500">
            The New York City Fire Code requires the periodic inspection and cleaning of exhaust systems for restaurant and other commercial cooking equipment that generate grease-laden vapors. Grease accumulations in exhaust systems are the source of numerous fires, which the exhaust ducts can spread throughout the building. The residue generated by wood-burning cooking equipment compounds the risk of a fire.
          </dd>
        </div>
  
        <div>
          <dt>
            <div class="flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
              <!-- Heroicon name: outline/lightning-bolt -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            <p class="mt-5 text-lg leading-6 font-medium text-gray-900">Smoke Tests</p>
          </dt>
          <dd class="mt-2 text-base text-gray-500">
            Section 810.3. outline all smoke tests in New York City.  Any faults or leaks found shall be corrected. A representative of the commissioner shall witness such a smoke test. In lieu thereof, the commissioner may accept the test report of a registered design professional responsible for the test, submitted in writing to the department.
          </dd>
        </div>
      </dl>
    </div>
</section>